name: Coverage Pages
on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coverage_pages:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    secrets: inherit
    with:
      python_version: "3.12"
      test_path: "test/unittests/"
      coverage_source: "ovoscope"
      install_extras: "audio,pydantic,media,listener,bench"
      deploy_pages: true
